---
- name: Provision application web server
  hosts: webservers
  become: true
  become_user: root
  remote_user: ubuntu
  vars:
    update_apt_cache: true
  module_defaults:
    apt:
      force_apt_get: true

  roles:
    - base
    - certbot
    - rabbitmq
    - web
    - celery
    - memcached
    - nginx
